### ISSUE TITLE
Problem - syntaxError

### ISSUE THREAD

**Issue by mx12mx12** [szymi-/fronius-to-influx#2]
Hi,
after "python src/prod.py' command I have an error:

Traceback (most recent call last):
  File "src/prod.py", line 1, in <module>
    from fronius_to_influx import FroniusToInflux
  File "/home/pi/fronius-to-influx-master/src/fronius_to_influx.py", line 30
    def __init__(self, client: InfluxDBClient, location: Location, endpoints: List[str], tz: Any) -> None:
                             ^
SyntaxError: invalid syntax

**Comment by mx12mx12** [comment]
Hi, I don't know to I do it, but works. :) (I was problem with influxdb plugin).
Works great!
Thanks Michal

**Comment by szymi-** [comment]
I am glad to hear that it works. Closing the issue for now.
